version: "3.8"
services:
  sonarqube:
    image: sonarqube:latest
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - "9000:9000"
    environment:
      - ES_JAVA_HOME=/opt/java/openjdk
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=admin
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarqube.rule=Host(`sonarqube.robdale.me.uk`)"
      - "traefik.http.routers.sonarqube.entrypoints=websecure"
      - "traefik.http.routers.sonarqube.tls.certresolver=letsencrypt"

volumes:
  sonarqube_conf:
    external: true
  sonarqube_data:
    external: true
  sonarqube_extensions:
    external: true

networks:
  frontend:
    external: true