version: "3.8"
services:
  postgresql:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rob
      POSTGRES_PASSWORD: <password>
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql:
    external: true
  postgresql-data:
    external: true