version: "2.1"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    networks:
      - frontend
    volumes:
      - heimdall-config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`home.robdale.me.uk`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls.certresolver=letsencrypt"

volumes:
  heimdall-config:
    external: true

networks:
  frontend:
    external: true