version: '3'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    networks:
      - frontend
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.robdale.me.uk`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"

volumes:
  grafana-data:
    external: true

networks:
  frontend:
    external: true