version: '3.4'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=<password>
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql/data

volumes:
  mssql-data:
    external: true