version: "3"

services:
  jenkins-blueocean:
    image: robdale110/jenkins-blueocean:2.332.3-1 
    container_name: jenkins-blueocean
    restart: on-failure
    networks:
      - frontend
    expose:
      - "8080"
    ports:
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://docker:2388
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.robdale.me.uk`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"

volumes:
  jenkins-data:
    external: true
  jenkins-docker-certs:
    external: true

networks:
  frontend:
    external: true
    
