version: '3'

services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.1-alpine
    networks:
      - frontend
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - /etc/influxdb2:/etc/influxdb2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.robdale.me.uk`)"
      - "traefik.http.routers.influxdb.entrypoints=websecure"
      - "traefik.http.routers.influxdb.tls.certresolver=letsencrypt"

volumes:
  influxdb-data:
    external: true

networks:
  frontend:
    external: true